### ISSUE TITLE
Why only accept http status 200?

### ISSUE THREAD

**Issue by yss14** [roccomuso/node-webhooks#11]
Why does node-webhooks only fire the `success` event, if the response has a http status code of `200`?
In my opinion at least `201` till `204` are also valid and common response codes.

**Comment by roccomuso** [comment]
Yep. You're right.
PR are welcome. :+1:

**Comment by yss14** [comment]
Should it be configable via options or hard coded?

**Comment by roccomuso** [comment]
@yss14 I guess we can easily hard-code for now..
A simple `[200, 201, 203, 204].indexOf(statusCode) !== -1` [here](https://github.com/roccomuso/node-webhooks/blob/master/index.js#L109) would be enough

**Comment by roccomuso** [comment]
Closed with #12
