### ISSUE TITLE
Pluggable Storage Adapter

### ISSUE THREAD

**Issue by manjeshpv** [roccomuso/node-webhooks#26]
@roccomuso thanks for the package, I'm using this node-webhooks in multiple projects/companies from around 3+ years

Simplicity and minimalist design of the node-webhooks helped in wide and faster adoption.

as the application scales, the reliability of the webhook delivery becomes challenging. Migrating from node-webhooks will additional learning for all developers across company.

After so much research, I thought to discuss with node-webhooks contributors to build 
- storage adapter
  - subscriptions
  - ingestion/deliveries - in case of spike/failures
  - logs
- UI for debugging
  - at production
  - while development

This requirement might not be in the code of this repo. but to discuss about overall integrations i created issue here

when there is no storage adapter is specified, automatically fallback to normal module

configurations should be there to tune based on use cases

for Persistence
- MongoDB
- MySQL/SQLite

for Messaging
- SQS/RabbitMQ
- Redis

For Logging
- ElasticSearch

For Debugging
- UI for Developer Debugging and Production failure retries
-

### Research
- https://hookdeck.io/

### Actions
**Phase1:**
- Logging
- Dashboard to retry
https://github.com/manjeshpv/node-webhooks-dashboard

**Comment by roccomuso** [comment]
Every PR is welcomed :D

**Comment by manjeshpv** [comment]
Hasura solves this problem
